### ISSUE TITLE
Summarize lab 6 - Sensor

### ISSUE THREAD

**Issue by LucasWaelti** [LucasWaelti/Lab-on-App-Summary#2]

**Comment by maximpavliv** [comment]
Done until 3.1 of the Lab. The last \begin{lstlisting} of the code on page 9 can't compile. Could you try plz?

**Comment by LucasWaelti** [comment]
I fixed it, that was an underscore issue. 
Replace `_` by `\_` as the underscore is reserved for math environment.

**Comment by LucasWaelti** [comment]
I completed the summary of lab 6, up to the beginning of chapter 5.1 (start of GPS)

**Comment by maximpavliv** [comment]
bogosse!

**Comment by maximpavliv** [comment]
I completed the 6a summary, we still have to summarize the 6b lab (about structure).

**Comment by maximpavliv** [comment]
Done
